#!/bin/bash

BORDER_COLOR="0xffc2e988" # aarrggbb
TARGET_BORDER_COLOR="0xffffcb62" # aarrggbb
BORDER_WIDTH=4
CHUNK_OFFSET=16

chunkc core::log_file stdout
chunkc core::log_level warn
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

# chunkwm-tiling plugin.
chunkc set custom_bar_enabled 1
chunkc set custom_bar_all_monitors 1
chunkc set custom_bar_offset_top 23
chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     $CHUNK_OFFSET
chunkc set global_desktop_offset_bottom  $CHUNK_OFFSET
chunkc set global_desktop_offset_left    $CHUNK_OFFSET
chunkc set global_desktop_offset_right   $CHUNK_OFFSET
chunkc set global_desktop_offset_gap     $CHUNK_OFFSET
chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0
chunkc set bsp_spawn_left                1
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5
chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1
chunkc set mouse_move_window             \"alt 1\"
chunkc set mouse_resize_window           \"alt 2\"
#chunkc set mouse_motion_interval         1000
chunkc set preselect_border_color        "$TARGET_BORDER_COLOR"
chunkc set preselect_border_width        $BORDER_WIDTH
chunkc set preselect_border_outline      0

# chunkwm-border plugin
chunkc set focused_border_color          "$BORDER_COLOR"
chunkc set focused_border_width          $BORDER_WIDTH
chunkc set focused_border_radius         8
# inline
chunkc set focused_border_outline        1
chunkc set focused_border_skip_floating  1
chunkc set focused_border_skip_monocle   0

# chunkwm-ffm plugin
chunkc set ffm_bypass_modifier           fn
chunkc set ffm_standby_on_float          1
chunkc set ffm_disable_autoraise         0

# Plugins to load when chunkwm starts
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

# Tiling rules
chunkc tiling::rule --owner Finder --name Copy --state float &
