let mapleader=" "
let maplocalleader=mapleader

set nocompatible
let loaded_netrwPlugin = 1 " disable netrw

filetype plugin on
syntax on

set path+=**
set shortmess=Iat
set showcmd
set softtabstop=2
  \ shiftwidth=2
  \ expandtab

" SignColumn
highlight SignColumn ctermbg=NONE

" add blank lines above and below, without insert
nnoremap <leader>O O<esc>j
nnoremap <leader>o o<esc>k

" substitute current word
nnoremap <Leader>s :%s/\<<C-r><C-w>\>/

source ~/dotfiles/vim/commentline.vim
source ~/dotfiles/vim/statusline.vim
source ~/dotfiles/vim/tabcomplete.vim

" fuzzy finder
set rtp+=/usr/local/opt/fzf
nnoremap <leader>f :FZF<CR>
