version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: Install
          shell: /bin/bash -l -eo pipefail
          command: |
            bash install.bash
            source ~/.bashrc
            type ls
            type ll
