version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: Install
          command: bash install.bash && source ~/.bashrc
      - run:
          name: Test ll alias
          command: ls -al ~/ && ll
