version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/dotfiles
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
    steps:
      - checkout
      - run:
          name: Install
          command: bash install.bash
      - run:
          name: Test
          command: type ll
