version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install
          command: bash install.bash && pwd && ls ~/

#      - run:
#          name: Test ll alias
#          command: source ~/.bashrc && ll
