# Load
files=(
  aliases.bash
  git-completion.bash
  git_utils.bash
  prompt.bash
  fuzzy.bash
  bashrc.linux
  bash_local)

for file in "${files[@]}"; do
  [ -r "$HOME/.$file" ] && source "$HOME/.$file"
done; unset file

# Editor
export VISUAL=vim
export EDITOR="$VISUAL"
