name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shell-check:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v2
    - name: install
      run: |
        REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git clone --bare $REPO
    - name: lint
      uses: azohra/shell-linter@v0.3.0
      with:
        path: .bashrc
