name: shellcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: azohra/shell-linter@v0.3.0
      env:
        SHELLCHECK_OPTS: -e SC1090 # Ignore SC1090: Can't follow non-constant source
      with:
        path: ".dotfiles/*.sh,.dotfiles/bin/*"
